name: Publish to maven repository
on:
  workflow_run:
    workflows: ["kvdb4j build"]
    types:
      - completed

jobs:
  deploy-maven:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Publish maven snapshot to OSS
        run: ./gradlew publishMavenPublicationToOssrhRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.KVDB4J_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.KVDB4J_SIGNING_PWD }}
